
title: "My New Hugo Site"

### This is the base configuration for the DES Prod Azure Subscription
### Base Hugo settings - overrides _default
baseURL: http://docs.des.ouh.nhs.uk/
environment: production
