
title: "[DEV] My New Hugo Site"

### This is the base configuration for the DES Dev Azure Subscription
### Base Hugo settings - overrides _default
baseURL: http://docs.dev.des.ouh.nhs.uk/
environment: development

